ARG STACK_VERSION
FROM heroku/heroku:$STACK_VERSION

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
  && apt-get install -y \
  build-essential \
  libtool \
  wget \
  python3-pip \
  ninja-build \
  pkg-config \
  meson

# use the heroku platform libraries when we can
#
# see https://devcenter.heroku.com/articles/stack-packages
#
# this should only pull in header files and should not create any extra run
# time dependencies
RUN apt-get install -y \
  glib-2.0-dev \
  libexpat1-dev \
  libpango1.0-dev \
  librsvg2-dev \
  libpng-dev \
  libspng-dev \
  libwebp-dev \
  libjpeg-turbo8-dev \
  libtiff5-dev \
  libexif-dev \
  liblcms2-dev \
  libxml2-dev \
  libfftw3-dev \
  libopenexr-dev \
  libopenjp2-7-dev \
  libpoppler-glib-dev \
  libimagequant-dev \
  liborc-0.4-dev \
  libarchive-dev \
  libcgif-dev \
  libheif-dev

WORKDIR /usr/local/src

# build to this prefix
#  - heroku has /usr/local/lib on the default ld.so.conf search path, so
#    this is convenient
#  - heroku has a basic dir structure in /usr/local, but no files
ARG PREFIX=/usr/local
ENV PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig

# Build liborc from source (not pre-installed on heroku-24)
ARG ORC_VERSION=0.4.32
ARG ORC_URL=https://gstreamer.freedesktop.org/src/orc

RUN wget ${ORC_URL}/orc-${ORC_VERSION}.tar.xz \
  && tar xf orc-${ORC_VERSION}.tar.xz \
  && cd orc-${ORC_VERSION} \
  && meson setup builddir \
  --prefix=${PREFIX} \
  -Dlibdir=lib \
  -Dlibexecdir=lib \
  --default-library=shared \
  && ninja -C builddir \
  && ninja -C builddir install

ARG VIPS_VERSION=8.17.3
ARG VIPS_URL=https://github.com/libvips/libvips/archive/refs/tags

RUN wget ${VIPS_URL}/v${VIPS_VERSION}/v${VIPS_VERSION}.tar.gz \
  && tar xzf v${VIPS_VERSION}.tar.gz \
  && cd libvips-${VIPS_VERSION} \
  && meson setup build \
  --prefix=$PREFIX \
  --libdir=lib \
  --buildtype=release \
  # obscure file format that nobody will use \
  -Dradiance=false \
  # obscure file format that nobody will use \
  -Danalyze=false \
  # modules cause issues with loading heif files in ruby-vips \
  -Dmodules=disabled \
  # allows omitting gobject-introspection library \
  -Dintrospection=disabled \
  && cd build \
  && meson compile \
  && meson install

# clean and package
ARG STACK_VERSION
RUN cd $PREFIX \
  && rm -rf bin/vipsprofile \
  && rm -rf lib/*.a lib/*.la lib/python* \
  && strip lib/lib*.so* \
  && rm -rf build \
  && mkdir -p build \
  && tar czf "build/heroku-${STACK_VERSION}.tar.gz" bin include lib \
  && ls -l build/heroku-${STACK_VERSION}.tar.gz \
  && echo built heroku-${STACK_VERSION}.tar.gz

# Update ldconfig cache
RUN ldconfig

# Store configuration for easy viewing in the repo
ARG STACK_VERSION
RUN cd $PREFIX \
  && echo "$ vips --vips-version" > "build/heroku-$STACK_VERSION.config.log" \
  && vips --vips-version >> "build/heroku-$STACK_VERSION.config.log" \
  && echo "" >> "build/heroku-$STACK_VERSION.config.log" \
  && echo "$ vips --vips-config" >> "build/heroku-$STACK_VERSION.config.log" \
  && vips --vips-config >> "build/heroku-$STACK_VERSION.config.log"
